# Generated by Django 4.2.16 on 2024-10-09 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.CharField(default=datetime.datetime(2024, 10, 9, 23, 14, 27, 633410, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
