# Generated by Django 4.2.16 on 2024-10-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
